### ISSUE TITLE
Show email html content in console

### ISSUE THREAD

**Issue by buob** [mojotech/modernator#24]
Currently it just shows 

```
server.1 | {:to dkurbz@gmail.com, :subject Get Started with Modernator!, :content <!DOCTYPE html>
```

:unamused:

**Comment by buob** [comment]
So it's impossible to get the signup link from the console

**Comment by sethkrasnianski** [comment]
[Foreman](http://ddollar.github.io/foreman/) is working just fine. I found an issue on github where some users were receiving the same truncated output https://github.com/ddollar/forego/issues/62.

Maybe just enforce foreman instead of forego forenow? :grin:
